version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    expose:
        - "80"
    volumes:
        - ./dist:/var/www/dist/:rw

  nodejs:
    build:
      context: ./docker/nodejs
      dockerfile: ./Dockerfile
    volumes:
        - .:/var/www/dist/:rw
